== mailman-on-tomcat

Everybody says that http://www.gnu.org/software/mailman/[Mailman] can't be made
to work under http://tomcat.apache.org[Tomcat], so I did it.

The basic mechanism is to enable the Tomcat 'cgi' servlet, map requiests on
/mailman to the cgi servlet, and create one-line Perl wrappers (in this
webapp's cgi directory) that invoke the actual cgi-bin.  This is because the
Tomcat servlet apparently requires an interpreter be used (without modifying
its source).

This project generates a War file that you just deploy to Tomcat and, on some systems,
it will just work out of the box.

=== HowTo

These instructions are for *Nix. Windows users will need more work. If you want help,
send money first.

# Clone this repo;
# cd into it;
# run the mkscripts shell script

You also have to ensure that the CGI scripts runs with the correct gid
(group id).  For example, on http://OpenBSD.org[OpenBSD (the secure server OS that I use)], I changed
master.passwd so that the _tomcat account is group www(67).

You also have to ensure that incoming mail runs with the correct gid.
Again op OpenBSD, change the _smtpd user to be in group daemon(1).

=== Remaining Problems

The paths in mkscript are hard-coded and will need to be tweaked if you installed mailman
somewhere else.

Icons don't work if you have them in the same deployment; pu them in a different web context,
or, figure out how to change the servlet-mappings (and let me know). Icons are only used on the 
home page, so they're not critical.


Also want to try this under WildFly (JBossAS 8.+), haven't had time yet.


