== mailman-on-tomcat

Everybody says that http://www.gnu.org/software/mailman/[Mailman] can't be made
to work under http://tomcat.apache.org[Tomcat], so I did it.

The basic mechanism is to enable the Tomcat 'cgi' servlet, map requiests on
/mailman to the cgi servlet, and create one-line Perl wrappers (in this
webapp's cgi directory) that invoke the actual cgi-bin.  This is because the
Tomcat servlet apparently requires an interpreter be used (without modifying
its source).

This project generates a War file that you just deploy to Tomcat and, on some systems,
it will just work out of the box.

=== HowTo

These instructions are for *Nix. Windows users will need more work. If you want help,
send money first.

* Clone this repo
* cd into it
* Examine the _mkscripts_ shell script; change the path in it if needed; run it in this directory.
* Run _mvn package_
* Run the deploy script, or otherwise install the target/*.war file as "mailman.war".

You also have to ensure that the CGI scripts runs with the correct gid
(group id). Either:

* Re-build Mailman with the configuration option to change the group id, or
* Change the user that Tomcat runs on to agree with what Mailman expects.
For example, on http://OpenBSD.org[OpenBSD (the secure server OS that I
use)], which provides pre-compiled packages of third-party software, I just
changed master.passwd so that the _tomcat account is group www(67). You need
to change permissions on some files that Tomcat is using.

You also have to ensure that incoming mail runs with the correct gid.
Same choices as above.
Again on OpenBSD, I changed the _smtpd user to be in group daemon(1).

*You will need to consider the security implications of these changes on your system
before making them*.

If necessary, change the IMAGE_LOGOS in your _/usr/local/lib/mailman/Mailman/mm_cfg.py_ to, e.g.:

	IMAGE_LOGOS = '/mailman/icons/'

=== Remaining Problems

Should put in an exec plugin in pom.xml to automate running of _mkscripts_.

The paths in mkscript are hard-coded and will need to be tweaked if you installed mailman
somewhere else.

Also want to try this under http://wildfly.org/[WildFly (JBossAS 8.+)], haven't had time yet.
